parameters:
#    nasty_cyber_workout.example.class: Nasty\CyberWorkoutBundle\Example

services:
#    nasty_cyber_workout.example:
#        class: %nasty_cyber_workout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
